// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  require(["danilo"], function(danilo) {
    var Document, User, user_login;
    danilo.router();
    User = (function(_super) {
      var password, url, username, validate_username;

      __extends(User, _super);

      function User() {
        return User.__super__.constructor.apply(this, arguments);
      }

      url = '/user/';

      username = '';

      password = '';

      validate_username = function(username) {
        return username.length > 3;
      };

      return User;

    })(danilo.Model);
    Document = (function(_super) {
      var get_title, is_public, pub, title, url;

      __extends(Document, _super);

      function Document() {
        return Document.__super__.constructor.apply(this, arguments);
      }

      url = '/document/';

      title = 'Untitled';

      pub = false;

      get_title = function() {
        return this.title;
      };

      is_public = function() {
        return this.pub;
      };

      return Document;

    })(danilo.Model);
    return user_login = new danilo.Operation({
      receive: ['form/submit/try_login']
    }, function(data) {
      console.log('got data', data);
      return alert('triggered event');
    });
  });

}).call(this);
