// Generated by CoffeeScript 1.3.3
(function() {

  require(["danilo"], function(danilo) {
    var Document, User, user_login;
    danilo.router();
    User = (function() {
      var password, url, username, validate_username;

      function User() {}

      url = '/user/';

      username = '';

      password = '';

      validate_username = function(username) {
        return username.length > 3;
      };

      return User;

    })();
    Document = (function() {
      var get_title, is_public, pub, title, url;

      function Document() {}

      url = '/document/';

      title = 'Untitled';

      pub = false;

      get_title = function() {
        return this.title;
      };

      is_public = function() {
        return this.pub;
      };

      return Document;

    })();
    return user_login = new danilo.Operation({
      receives: ['form/submit/try_login']
    }, function(sender) {
      console.log(sender);
      return alert('triggered event');
    });
  });

}).call(this);
